import { District, State, Block, Village } from "../models/index.js";



const villageData = [
    {
        "state": "Bihar",
        "districts": [
            {
                "name": "Nawada",
                "blocks": [
                    {
                        "name": "Akbarpur",
                        "villages": [
                            "Aima",
                            "Akbarpur",
                            "Andhrijhund",
                            "Asa Bigaha",
                            "Ashrafpur",
                            "Aswan",
                            "Baghnan",
                            "Bakhwa Jagir",
                            "Baksanda",
                            "Baliya Buzurg",
                            "Baliya Khurd",
                            "Bandarkol",
                            "Barew",
                            "Barhori",
                            "Bela",
                            "Bhanail Lodipur",
                            "Bhat Bigha",
                            "Bhumai",
                            "Bishunpur",
                            "Budhuwa",
                            "Burail",
                            "Chandauli",
                            "Chandipur",
                            "Chaparhat",
                            "Chhapra",
                            "Chhotka Amwan",
                            "Dadpur",
                            "Daiwa",
                            "Dakra",
                            "Dariyapur",
                            "Dariyapur Siram",
                            "Dbobghatti",
                            "Derawan",
                            "Derhgawan",
                            "Dewara",
                            "Dhandhari",
                            "Dhangariya",
                            "Dhanwara",
                            "Dihi",
                            "Diri",
                            "Dudhaili",
                            "Dulah Bigaha",
                            "Fatehpur",
                            "Gangta",
                            "Garandi",
                            "Ghazipur",
                            "Gobind Bigaha",
                            "Gogan Karhari",
                            "Gopalpur",
                            "Gopalpur",
                            "Gonam Bigha",
                            "Gujan Kahar",
                            "Gur Chak",
                            "Harnagarpur",
                            "Indaul",
                            "Inguna",
                            "Itwa",
                            "Jagan Karhari",
                            "Jagatpur",
                            "Jakhe",
                            "Jalalpur",
                            "Jamghat",
                            "Jasauli",
                            "Kajhia",
                            "Kalaunda",
                            "Kalaundi",
                            "Kannauj",
                            "Karam",
                            "Karanpur",
                            "Kashi Choan",
                            "Kendua",
                            "Khaira",
                            "Khaira Buzurg",
                            "Khanpura",
                            "Koiri Bigaha",
                            "Kuhila",
                            "Kulna",
                            "Kumhar Bigaha",
                            "Ladaha",
                            "Lakhmohna",
                            "Lakshmi Bigha",
                            "Lodipur",
                            "Lohanipur",
                            "Losinghani",
                            "Madaini",
                            "Madhipur",
                            "Madhopur",
                            "Mahanandpur",
                            "Mahapur",
                            "Maheshdih",
                            "Mahiman Bigaha",
                            "Mahugain Khurd",
                            "Mahunar",
                            "Malikpur",
                            "Mane Bigaha",
                            "Mankhar",
                            "Manpur",
                            "Marufpur",
                            "Mastanganj",
                            "Meanpur",
                            "Mohanandpur",
                            "Mohanpur",
                            "Mohibbi",
                            "Mohanan Bigha",
                            "Mundipur",
                            "Musaini",
                            "Nad",
                            "Nagwan",
                            "Nanauri",
                            "Nonai",
                            "Oraiya",
                            "Pachgaon",
                            "Pachrukhi",
                            "Pachtarwa",
                            "Paharpur",
                            "Pajuna",
                            "Pakari",
                            "Panti",
                            "Parato Karhari",
                            "Pasiyakalan",
                            "Pasiya Khurd",
                            "Patangi",
                            "Patori",
                            "Patrang",
                            "Pharaha",
                            "Phulwan",
                            "Pindrawan",
                            "Pipra Khurd",
                            "Piraunta",
                            "Pithauri",
                            "Pokhra",
                            "Pranpur",
                            "Qazihant",
                            "Rajahat",
                            "Rajpur",
                            "Ramdewa",
                            "Ramdiha",
                            "Rampur",
                            "Ratanpur",
                            "Runnipur",
                            "Sadipur",
                            "Saman Pachrukhi",
                            "Sanokhra",
                            "Sanrhauli",
                            "Sapto",
                            "Sawaiya",
                            "Shahpur",
                            "Shahpur Jhilwariya",
                            "Shakarpura",
                            "Shekhpura",
                            "Sherpur",
                            "Sirampur",
                            "Sirkata",
                            "Sirpat",
                            "Supai",
                            "Supaul",
                            "Surjpura",
                            "Tear",
                            "Tejmal",
                            "Telbadro",
                            "Thekahi",
                            "Tinsisiya",
                            "Udaikhap"
                        ]
                    },
                    {
                        "name": "Govindpur",
                        "villages": [
                            "Alipur",
                            "Amahra",
                            "Az Raqbe Khakhanduwa",
                            "Baharagawan",
                            "Bahiara",
                            "Baksauti",
                            "Baliya",
                            "Baniya Bigaha",
                            "Baratanr",
                            "Barhai Bigha",
                            "Bela",
                            "Belarua",
                            "Bhawanpur",
                            "Bishunpur",
                            "Budhwara",
                            "Daniyar",
                            "Delhua",
                            "Dhakni",
                            "Dhanpuri",
                            "Dilhua",
                            "Dulardih",
                            "Ekamba",
                            "Ektara",
                            "Ektia",
                            "Gangadih",
                            "Gangata",
                            "Garandih",
                            "Gautam",
                            "Gyar",
                            "Ghanta",
                            "Ghurmuriya",
                            "Gobindpur",
                            "Hanra",
                            "Harnarayanpur",
                            "Jaipur",
                            "Jalalpur",
                            "Jamghat",
                            "Jatsari",
                            "Kamalpur",
                            "Karahra",
                            "Karahri",
                            "Kasikhati",
                            "Katru Chak",
                            "Khairakhurd",
                            "Khakhanduwa",
                            "Kharsan",
                            "Koriyauna",
                            "Kulja",
                            "Kumhar Bigaha",
                            "Kumhiya",
                            "Madhopur",
                            "Mahavara",
                            "Mahugain",
                            "Misir Chak",
                            "Pahraitha",
                            "Pandariya",
                            "Parsauni",
                            "Patandei",
                            "Pathra",
                            "Patluka",
                            "Pharka",
                            "Pipra",
                            "Pipra",
                            "Puraini",
                            "Rampur",
                            "Ratni",
                            "Sarbahanpur",
                            "Sarkanda",
                            "Sikariya",
                            "Sughari",
                            "Tetariya",
                            "Thali Buzurg",
                            "Thali Khurd",
                            "Tupariya"
                        ]
                    },
                    {
                        "name": "Hisua",
                        "villages": [
                            "Amhri",
                            "Ariyan",
                            "Bagodar",
                            "Bajra",
                            "Baliyari",
                            "Barhauna",
                            "Belaru",
                            "Bhadseni",
                            "Bhelwa",
                            "Budhaul",
                            "Chhatiar",
                            "Chitarghatti",
                            "Daulatpur",
                            "Dhamol",
                            "Dhanawan",
                            "Dheuri",
                            "Dhurihar",
                            "Dihuri",
                            "Dona",
                            "Dumri",
                            "Eknar",
                            "Ghuriha",
                            "Gonar Bigha",
                            "Hadsa",
                            "Hisua Chak Urf Milki",
                            "Kaithir",
                            "Karamchak",
                            "Kazi Bigha",
                            "Kendua",
                            "Khanpur",
                            "Latawar Faridpur",
                            "Mahammapur",
                            "Mahdewa",
                            "Majhwe",
                            "Manawan",
                            "Marua",
                            "Matuk Bigha",
                            "Maulanagar",
                            "Nasratpur Phulwariya",
                            "Pacharha",
                            "Panda Chak",
                            "Ranipur",
                            "Sachaul",
                            "Sakra",
                            "Sighauli",
                            "Sinhin",
                            "Sinhinchak",
                            "Sirampur",
                            "Sonsa",
                            "Tungi",
                            "Urasa",
                            "Uttam",
                            "Mohammadpur"
                        ]
                    },
                    {
                        "name": "Kashi Chak",
                        "villages": [
                            "Bauri",
                            "Bazidpur",
                            "Belar",
                            "Bhagwatpur",
                            "Bhatta",
                            "Birnanwan",
                            "Chandi Nuwan",
                            "Daula Chak",
                            "Derhgaon",
                            "Dewan Bigha",
                            "Dhanpur",
                            "Dhanpur Chak",
                            "Dhota",
                            "Dihri",
                            "Kakhari",
                            "Kashi Chak",
                            "Kosthua",
                            "Maharath",
                            "Makhdumpur Chak",
                            "Milki",
                            "Milki Chak",
                            "Nepura",
                            "Pali",
                            "Parbati",
                            "Pojh",
                            "Rasul Chak",
                            "Rewara Jagdishpur",
                            "Sarkatti",
                            "Shakarganj",
                            "Sikandarpur",
                            "Subhanpur",
                            "Sumbha",
                            "Uprawan"
                        ]
                    },
                    {
                        "name": "Kawakole",
                        "villages": [
                            "Bara",
                            "Baraun",
                            "Bhanwarkol",
                            "Bishunpur",
                            "Bukar",
                            "Chahal",
                            "Charaul",
                            "Chhabail",
                            "Chihutiya",
                            "Darawan",
                            "Dewangarh",
                            "Gokhain",
                            "Jogna",
                            "Kadahar",
                            "Katni",
                            "Kawakol",
                            "Kewali",
                            "Khaira",
                            "Kharsari",
                            "Kutub Chak",
                            "Lalpur",
                            "Madhurapur",
                            "Mahapur",
                            "Mahuliyatanr",
                            "Mahurar",
                            "Majhila",
                            "Mananpur",
                            "Manrara",
                            "Mansagar",
                            "Nawadih",
                            "Okhariya",
                            "Pachamba",
                            "Paharpur",
                            "Pali",
                            "Panre Gangaur",
                            "Patori",
                            "Pharahda",
                            "Phul Dih",
                            "Ranigadar",
                            "Rupi",
                            "Rustampur",
                            "Sabada",
                            "Salaiya",
                            "Santhe",
                            "Sarauni",
                            "Singhna",
                            "Sokhodewara",
                            "Sundari"
                        ]
                    },
                    {
                        "name": "Meskaur",
                        "villages": [
                            "Adganwan",
                            "Alawan",
                            "Ankri Panre Bigha",
                            "Arandi",
                            "Arghu Chak",
                            "Bandhi",
                            "Barat",
                            "Barosar",
                            "Belwan",
                            "Biju Bigha",
                            "Bisiait",
                            "Chanda Bara",
                            "Chandardei",
                            "Chanrsara",
                            "Chorabara",
                            "Dariyapur",
                            "Dewara",
                            "Dhanganwan",
                            "Dhonrhra",
                            "Gamhira",
                            "Ganga Bara",
                            "Gobindpur Urf Qanungo Bigha",
                            "Gotauli",
                            "Harla",
                            "Hero",
                            "Jamui Pakariya",
                            "Jarahiya",
                            "Jhikatia",
                            "Katghara",
                            "Kaua Bara",
                            "Kopin",
                            "Lakhaura",
                            "Lodipur Chak",
                            "Mahugain",
                            "Majhila",
                            "Meksaur",
                            "Merhkuri",
                            "Milki",
                            "Mirzapur",
                            "Murehta Chak",
                            "Nadgarh",
                            "Nadsena",
                            "Niman",
                            "Noni",
                            "Paroria",
                            "Pasarhi",
                            "Pasia",
                            "Pathra",
                            "Pawai",
                            "Rampur",
                            "Ranka Jalalpur",
                            "Rasulpur",
                            "Repura Sirsa",
                            "Saraye",
                            "Satua",
                            "Shekhabara",
                            "Sonpura",
                            "Tali",
                            "Tetaria",
                            "Woraina"
                        ]
                    },
                    {
                        "name": "Nardiganj",
                        "villages": [
                            "Adampur",
                            "Anarpur Pakariya",
                            "Babhnauli",
                            "Baguli",
                            "Bhadaur",
                            "Bhalua",
                            "Bhelu Bigha",
                            "Biku",
                            "Chiraia",
                            "Chourma",
                            "Dalelpur",
                            "Dariyapur",
                            "Deali Bigha",
                            "Dhaniyawan",
                            "Dohra",
                            "Domawar",
                            "Gotrayan",
                            "Hanriya",
                            "Ichua Karna",
                            "Jaddupur",
                            "Jagdishpur",
                            "Janpura",
                            "Kahuara",
                            "Khushihal Bigha",
                            "Kosla",
                            "Kujha",
                            "Lodipur Jafra",
                            "Madhuban",
                            "Masaurha",
                            "Miyan Bigha",
                            "Mutanaze",
                            "Nandgram",
                            "Nandpur Chamarua",
                            "Nardiganj",
                            "Nenaura",
                            "Pacheya",
                            "Pakariya",
                            "Panrupa",
                            "Pararia",
                            "Parman",
                            "Partappur",
                            "Pasai",
                            "Pes",
                            "Phaldu",
                            "Qazi Bigha",
                            "Rajapur",
                            "Rajaur",
                            "Rame Fazilpur",
                            "Rampur",
                            "Sabhri",
                            "Sahajpura",
                            "Saidpur Pakariya",
                            "Sandalpur",
                            "Sandohro",
                            "Woro"
                        ]
                    },
                    {
                        "name": "Narhat",
                        "villages": [
                            "Abgil",
                            "Akhra",
                            "Babhnaur",
                            "Badalpur",
                            "Bajo Chak",
                            "Baniya Bigha",
                            "Bara",
                            "Bara Khurd",
                            "Barauli",
                            "Barauli Chak",
                            "Barauta",
                            "Bazidpur",
                            "Bhikhanpura",
                            "Bhim Bigha",
                            "Chainpura",
                            "Chanda Chak",
                            "Chatar",
                            "Dai Bigha",
                            "Dargahi Bigaha",
                            "Daulatpur",
                            "Derhgaon",
                            "Dewara",
                            "Ekamba",
                            "Gajra",
                            "Gangapur",
                            "Gangta",
                            "Garo Bigha",
                            "Guru Chak",
                            "Hansa Chak",
                            "Hansapur",
                            "Hasanpur",
                            "Hazi Dhab",
                            "Hazratpur",
                            "Jalalpur",
                            "Jamuara",
                            "Jasa Chak",
                            "Jhikarua",
                            "Karman",
                            "Khanawan",
                            "Konibar",
                            "Kusa",
                            "Mayapur",
                            "Milki",
                            "Misir Chak",
                            "Narayanpur",
                            "Narhat",
                            "Nawada",
                            "Pali Kalan",
                            "Pali Khurd",
                            "Panre Chak",
                            "Patal Bigha",
                            "Punaul",
                            "Punthar",
                            "Qazipura",
                            "Raja Bigha",
                            "Rampur Dhorhan",
                            "Saidapur Goasa",
                            "Saidpur",
                            "Shah Ghazipur",
                            "Shah Ghazipur",
                            "Shekhpura",
                            "Sinduari",
                            "Tarupur",
                            "Walipur",
                            "Walipur Chehal Chak"
                        ]
                    },
                    {
                        "name": "Nawada",
                        "villages": [
                            "Akauna Minhai",
                            "Akauna Nizamat",
                            "Amipur",
                            "Anandpura",
                            "Asarhi",
                            "Asarhi",
                            "Balokhar",
                            "Barawan",
                            "Barhai Bigha",
                            "Bermi",
                            "Bhadauni (CT)",
                            "Bhadokhara",
                            "Bhagwanpur",
                            "Bharaunsa",
                            "Bhola Bigha",
                            "Bhuraha",
                            "Bibipura",
                            "Budhaul",
                            "Chamardiha",
                            "Daulatiya",
                            "Dhibri Chak",
                            "Didaur",
                            "Ghanghauli",
                            "Ghaus Chak Milki",
                            "Ghausnagar",
                            "Gondapur",
                            "Gosta Wan",
                            "Harla",
                            "Husain Chak",
                            "Husain Chak",
                            "Jai Singh Bigha",
                            "Jamuawan Patwa Saray",
                            "Jharayan",
                            "Jhiktaura",
                            "Jhunathi",
                            "Kabirpur",
                            "Kadirganj",
                            "Kena",
                            "Kendua",
                            "Khaparahi",
                            "Kharant",
                            "Khutauni Chak",
                            "Khutika",
                            "Kurma",
                            "Loharpura",
                            "Lohra",
                            "Magura Khurd",
                            "Mahuli",
                            "Majhanpura",
                            "Mangra",
                            "Mohiuddinpur",
                            "Nanaura",
                            "Nawada Urf Gonawa",
                            "Neya",
                            "Odhanpur",
                            "Oraina",
                            "Pachhiyadih",
                            "Pakaria",
                            "Pathra English",
                            "Paura",
                            "Pipra Chak",
                            "Qadirganj",
                            "Saheb Chak",
                            "Samai",
                            "Sharif Chak",
                            "Sidesarpur",
                            "Sikandara",
                            "Sikandarpur",
                            "Siswan",
                            "Sohjana",
                            "Sonsihari",
                            "Tetariya",
                            "Ursa",
                            "Worhanpur",
                            "Zaki Chak"
                        ]
                    },
                    {
                        "name": "Pakribarawan",
                        "villages": [
                            "Akauna",
                            "Anjunar",
                            "Arsaniya",
                            "Asawan",
                            "Baliari",
                            "Baliyari Buzurg",
                            "Bardiha",
                            "Barhauna",
                            "Bazidpur",
                            "Belkhunda",
                            "Bhagwanpur Khapura",
                            "Bihta",
                            "Budhauli",
                            "Datraul",
                            "Dhamaul",
                            "Dharahra",
                            "Dhewadha Chhatarwar",
                            "Dhonrah",
                            "Diaura",
                            "Dola",
                            "Dumrawan",
                            "Dumri",
                            "Gulni",
                            "Hasna",
                            "Hathiauri",
                            "Hunrarahi",
                            "Iruri",
                            "Jakhaur",
                            "Jalpar",
                            "Jamhariya",
                            "Jasat",
                            "Jiuri",
                            "Kachna",
                            "Kapsandi",
                            "Kawala",
                            "Keshori",
                            "Kharant",
                            "Kunanpur",
                            "Kurhaita",
                            "Lachhmipur",
                            "Lilo",
                            "Lodipur",
                            "Madhepur",
                            "Maheshpur",
                            "Marawa",
                            "Meghipur",
                            "Mehdipur",
                            "Milki",
                            "Nejai",
                            "Odhpura",
                            "Pakri Barwan",
                            "Parariya",
                            "Poksi",
                            "Rais",
                            "Rampur",
                            "Rewar",
                            "Rewar",
                            "Rohuwa",
                            "Semariya",
                            "Senduara",
                            "Shamdewa",
                            "Shekhpura",
                            "Tanpura",
                            "Thalpos",
                            "Tirwa",
                            "Turkban",
                            "Ukaura",
                            "Wairani"
                        ]
                    },
                    {
                        "name": "Rajauli",
                        "villages": [
                            "Adhbarwa",
                            "Adwaria",
                            "Amawan",
                            "Amba",
                            "Amghati",
                            "Andharbari",
                            "Angaia",
                            "Aswatari",
                            "Babhni",
                            "Bagdewa",
                            "Baghmari",
                            "Bahadurpur",
                            "Bajida",
                            "Bajwatari",
                            "Bakhori",
                            "Baliya",
                            "Bandan Chhapra",
                            "Bara",
                            "Barachuan",
                            "Barahar",
                            "Baratanr",
                            "Baurhi Kalan",
                            "Baurhi Khurd",
                            "Belam",
                            "Bhaiji Bhita",
                            "Bhalui",
                            "Bhane Khap",
                            "Bhanrra",
                            "Bhatauliya",
                            "Bhaunr",
                            "Bhitiya",
                            "Bhupatpur",
                            "Bigha",
                            "Bijban",
                            "Biraj",
                            "Burhiya Sankh",
                            "Chamar Bigha",
                            "Chamotha",
                            "Chanahi",
                            "Chandebara",
                            "Chaphel",
                            "Chapwatari",
                            "Chargharwa",
                            "Chatkari",
                            "Chhatni",
                            "Chiraila",
                            "Chitarkoli",
                            "Chordiha",
                            "Choutha",
                            "Damodarpur",
                            "Delwa",
                            "Dhab",
                            "Dhalha",
                            "Dhamaul",
                            "Dhamni",
                            "Dhamu Chak",
                            "Dhuritanr",
                            "Dopta",
                            "Dudhi Mati",
                            "Dufera",
                            "Dularpura",
                            "Dumarkol",
                            "Dumri",
                            "Gagan Buzurg",
                            "Gagan Khurd",
                            "Garh Dibaur",
                            "Gariba",
                            "Ghasiadih",
                            "Ghat Pokhrawan",
                            "Ghatsatgir",
                            "Ghorwa Chatan",
                            "Gopalpur",
                            "Gosaintari",
                            "Hardiya",
                            "Hatho Chak",
                            "Hirakhan",
                            "Hiro Dih",
                            "Horila",
                            "Jagduari",
                            "Jahura",
                            "Jainagra",
                            "Jhirkhi",
                            "Job Kalan",
                            "Jogijot",
                            "Jogna Tilha",
                            "Jogni",
                            "Jogni Kanak Jot",
                            "Jogya Maran",
                            "Jorasimar",
                            "Kairikhap",
                            "Kamra Usman",
                            "Karanpur",
                            "Karanpur",
                            "Karigawan",
                            "Karma Kalan",
                            "Kendua",
                            "Khairachuan",
                            "Khajuri",
                            "Kharahwatanr",
                            "Khijua",
                            "Khirkiya Kalan",
                            "Khusihali Bhita",
                            "Kodwaria",
                            "Kola",
                            "Kumbhiyatari",
                            "Kumharua",
                            "Kumhiyatari",
                            "Kusdariya",
                            "Kutlupur",
                            "Langura",
                            "Lat",
                            "Madhorampur",
                            "Mahiara",
                            "Mahkama",
                            "Mahsai",
                            "Mahua Tanr",
                            "Majhila",
                            "Majhila Seum",
                            "Manbhagwa",
                            "Mandih",
                            "Mangodih Gangtia",
                            "Manjhla Dih",
                            "Marmon",
                            "Matha Dih",
                            "Mohanpur",
                            "Mudakar",
                            "Murhena",
                            "Nadgarha",
                            "Nagarwatari",
                            "Pahwa Chak",
                            "Palanki",
                            "Pandna",
                            "Panraya",
                            "Panti",
                            "Panwankalan",
                            "Parariya",
                            "Parka Buzurg",
                            "Partauniyan",
                            "Pasraila",
                            "Pelmo",
                            "Phulwariya Kalan",
                            "Phulwariya Khurd",
                            "Pichhli",
                            "Pindpurwa",
                            "Pipra",
                            "Purnajob",
                            "Purna Singar",
                            "Rajauli",
                            "Ramdasi",
                            "Raniwans",
                            "Ratanpur",
                            "Sabalpur Chorni",
                            "Salempur",
                            "Saraiya",
                            "Sario",
                            "Sarki",
                            "Satgir",
                            "Sawaia Tanr",
                            "Sili Dubaur",
                            "Singar Khas",
                            "Sirodabar",
                            "Sobhwa Maran",
                            "Sohda",
                            "Suarleti",
                            "Takuatar",
                            "Targir",
                            "Tilaiya",
                            "Totrahi",
                            "Usman"
                        ]
                    },
                    {
                        "name": "Roh",
                        "villages": [
                            "Adampur",
                            "Amba Chak",
                            "Anaila",
                            "Baghor",
                            "Bajwara",
                            "Baliari",
                            "Bansi Chak",
                            "Bara",
                            "Bara Chak",
                            "Barail",
                            "Beldhi",
                            "Bhandajor",
                            "Bhatta",
                            "Bhikhampur",
                            "Binayak",
                            "Chhanaun",
                            "Chorwar",
                            "Dewanag",
                            "Dewanpura",
                            "Dhanawan",
                            "Dirmo Bara",
                            "Duari",
                            "Dumri",
                            "Gayawali Bigha",
                            "Ghorahi",
                            "Gointhadih",
                            "Gorihari",
                            "Hamaza Chak",
                            "Harsidhpur",
                            "Isepur",
                            "Jalalpur",
                            "Japhra",
                            "Jhakhor",
                            "Karanpur",
                            "Karman",
                            "Kasmara",
                            "Katahra",
                            "Kathaun",
                            "Kazi Chak",
                            "Khargu Bigha",
                            "Kharij Jaman",
                            "Khetal Bigha",
                            "Kosirukhi",
                            "Kumhrawan",
                            "Kunda",
                            "Kunj",
                            "Kusdihra",
                            "Mahrawan",
                            "Mahuli",
                            "Makhdumpur",
                            "Marra",
                            "Marui",
                            "Morawan",
                            "Nazardih",
                            "Pachamba",
                            "Pachghara",
                            "Pachohya",
                            "Paltu Chak",
                            "Partabpur Nizamat",
                            "Phatna",
                            "Pipra",
                            "Pratabpur Jagir",
                            "Pratabpur Khalsa",
                            "Ratoi",
                            "Roh",
                            "Rupau",
                            "Rustampur",
                            "Sadikpur",
                            "Samhri",
                            "Santhe",
                            "Sekharpur",
                            "Sheikhpura",
                            "Sitapur",
                            "Siur",
                            "Tajpur",
                            "Telari",
                            "Wohari"
                        ]
                    },
                    {
                        "name": "Sirdala",
                        "villages": [
                            "Abdul",
                            "Adeya",
                            "Akauna",
                            "Amhadi",
                            "Amjhari",
                            "Amokhari",
                            "Babhni",
                            "Baijnathpur",
                            "Banauli",
                            "Bandhi",
                            "Barahkol",
                            "Bargawan",
                            "Barhi Bigha",
                            "Barsot",
                            "Berri",
                            "Bhalua",
                            "Bharsanda",
                            "Bhatauliya",
                            "Bhita",
                            "Bhitiya",
                            "Bilarpur",
                            "Chaili",
                            "Chamotha",
                            "Chaube",
                            "Chaugawan",
                            "Chaukia",
                            "Chhamuha",
                            "Chhonu Bigha",
                            "Chiraia",
                            "Dehberri",
                            "Dhab",
                            "Dhiraundh",
                            "Duari",
                            "Dudhaili",
                            "Dumri",
                            "Fatehpur",
                            "Ghaghat",
                            "Ghat Bakshila",
                            "Goriadda",
                            "Hajrakhap",
                            "Hemza Bharath",
                            "Hemza Dewpal",
                            "Ismailpur",
                            "Jagdishpur",
                            "Jamuganin",
                            "Janhaul",
                            "Jharna",
                            "Kadwara",
                            "Karman Khurd",
                            "Kendua",
                            "Khalkhu",
                            "Khanpura",
                            "Kharaun",
                            "Khatangi",
                            "Kuldiha",
                            "Kusahan",
                            "Laun",
                            "Lodipur Chak",
                            "Lohgarwa",
                            "Machan",
                            "Mahmad Nagar",
                            "Majhauli",
                            "Majhila Auwal",
                            "Marrhi Kalaunda",
                            "Mohbatpur",
                            "Nad",
                            "Narauli",
                            "Nawada",
                            "Nawadih",
                            "Noni",
                            "Padmaul",
                            "Paranpur",
                            "Parsa",
                            "Partabpur",
                            "Partappur",
                            "Pukhariyakol",
                            "Rabio",
                            "Rajanr",
                            "Rajaundh",
                            "Rupai",
                            "Sanrh Majhganw",
                            "Shahpur",
                            "Sidhaul",
                            "Sirdala",
                            "Sonwe",
                            "Takiya",
                            "Taran",
                            "Thamkola",
                            "Upardih"
                        ]
                    },
                    {
                        "name": "Warisaliganj",
                        "villages": [
                            "Abdalpur",
                            "Ahri Chak",
                            "Apsand",
                            "Azampur",
                            "Baghi Bardiha",
                            "Bahera Bhelwa",
                            "Bahroi Chak",
                            "Bala Chak",
                            "Bali",
                            "Ballopur",
                            "Bandha",
                            "Barrawan",
                            "Baso Chak",
                            "Begrajpur",
                            "Bhalua",
                            "Bheria",
                            "Bhikhari Chak",
                            "Bojhwan",
                            "Chakwae",
                            "Chalisa Chak",
                            "Chandipur",
                            "Chanpur",
                            "Chanpura",
                            "Chiraia",
                            "Dani Chak",
                            "Dariapur",
                            "Daulatpur",
                            "Dosut",
                            "Fataha",
                            "Gamhirpur Sonbarsa",
                            "Gangta",
                            "Garua",
                            "Haibatpur",
                            "Hajipur",
                            "Hemda",
                            "Jamuawan",
                            "Kandha",
                            "Kathokari",
                            "Khaira",
                            "Khajpura",
                            "Khanapur",
                            "Khirbhojana",
                            "Kochgawan",
                            "Kumbhi",
                            "Kutri",
                            "Mahiye",
                            "Mai",
                            "Makanpur",
                            "Makanpur Job",
                            "Manjaur",
                            "Masuda",
                            "Milki",
                            "Milki",
                            "Mohiuddinpur",
                            "Mohiuddinpur",
                            "Mosima",
                            "Motalib Chak",
                            "Murgia Chak",
                            "Naromurar",
                            "Pachwara",
                            "Paingari",
                            "Raikar",
                            "Rajapur",
                            "Rampur",
                            "Rasanpur",
                            "Saur",
                            "Sawaiya",
                            "Shahpur",
                            "Shekhpurwa",
                            "Sorahipur",
                            "Sorahipur",
                            "Sultanpur",
                            "Sultanpur",
                            "Thera",
                            "Mafi",
                            "Murla Chak",
                            "Sami Chak",
                            "Sherpur",
                            "Simri"
                        ]
                    }
                ]
            }
        ]
    },
    {
        state: "Jharkhand",
        districts: [
            {
                "name": "Koderma",
                "blocks": [
                    {
                        "name": "Chandwara",
                        "villages": [
                            "Aragaro",
                            "Chokhandi",
                            "Joungi",
                            "Nawadih",
                            "Puto",
                            "Sardarodih",
                            "Badkidhamrai",
                            "Chhotki Dhamrai",
                            "Manjhgawan",
                            "Simaria",
                            "Bendi",
                            "Bhittia",
                            "Bilaro",
                            "Biragadha",
                            "Birhorwa",
                            "Bongadag",
                            "Chenganwatand",
                            "Chhatara",
                            "Chourhi Chattan",
                            "Ghatodabar",
                            "Ghodtappi",
                            "Hathgaswa",
                            "Kumbhiatari",
                            "Marmotari",
                            "Okerchuan",
                            "Ratansot",
                            "Sindri",
                            "Bhondo",
                            "Chourahi",
                            "Ghutitand",
                            "Mahuadohar",
                            "Piprahi",
                            "Birsodih",
                            "Chamgudokalan",
                            "ChamgudoKhurd",
                            "Charkipahri",
                            "Garagadgi",
                            "Harli",
                            "Jamkati",
                            "Larabad",
                            "Tetarchak",
                            "Bandidigthu",
                            "Chandwara",
                            "Baradih",
                            "Chandwara",
                            "Chilodih",
                            "Gaangodih",
                            "Mahugai",
                            "Bajpur",
                            "Belkhara",
                            "Chandraghati",
                            "Garaidih",
                            "Gawanpur",
                            "Jolhakarma",
                            "Kanko",
                            "Kurm idih",
                            "Pindaro",
                            "Kanti",
                            "Murtia",
                            "Dhab",
                            "Gajure",
                            "Khandi",
                            "Barkikaraunjia",
                            "Chhotkikaraunjia",
                            "Madangundi",
                            "Harino",
                            "Pathalgadda",
                            "Titirchanch",
                            "Yogidih",
                            "Arniyamo",
                            "Bandachak",
                            "Bidar",
                            "Debodih",
                            "Digthu",
                            "Gaida",
                            "Kasiadih",
                            "Lodhni",
                            "Mayadih",
                            "Pipradih",
                            "Pokdanda",
                            "Bara",
                            "Chuanbar",
                            "Durginia",
                            "Kanti.",
                            "Mahthadih",
                            "Purnatham",
                            "Tham",
                            "Kotwardih",
                            "Urwan",
                            "Maryopara"
                        ]
                    },
                    {
                        "name": "Domchanch",
                        "villages": [
                            "Bachhedih",
                            "Bhimedih",
                            "Bindomoh",
                            "Jamdiha",
                            "Kailakhandahar",
                            "Karmo",
                            "Kusmai",
                            "Singhpur",
                            "Taratand",
                            "Bagdo",
                            "Dumardiha",
                            "Pratango",
                            "Bagridih",
                            "Barahmasia",
                            "Hariharpur",
                            "Lachhandih",
                            "Nawadih.",
                            "Ahraai",
                            "Bangakhalar",
                            "Garmundo",
                            "Kabrabut",
                            "Karmikund",
                            "Nawadih",
                            "Padaria",
                            "Behradih",
                            "Gharbariavar",
                            "Kisunpur",
                            "Pahridih",
                            "Pakaria",
                            "Saroun",
                            "Chahalwatari",
                            "Dhab",
                            "Ekbanwa",
                            "Galkato",
                            "Goriadih",
                            "Kusiyaro",
                            "Lakshmibathaan",
                            "Nutankharia",
                            "Tarai",
                            "Baidbar",
                            "Banpok",
                            "Devpur",
                            "Dhargawan",
                            "Koldiha",
                            "Lakshmipur",
                            "Matihani",
                            "Navdiha",
                            "Pandnatand",
                            "Paranwatand",
                            "Sersingha",
                            "Sitoia",
                            "Chak",
                            "Dhodhakola",
                            "Haraia",
                            "Jamuniatand",
                            "Kushahna",
                            "Nalwa",
                            "Pasia",
                            "Samsiharia",
                            "Tilaiatand",
                            "Chainpur Alias Chanmanai",
                            "Domchanch (CT)",
                            "Maheshpur",
                            "Taratand",
                            "Domchanch (CT)",
                            "Domchanch (CT)",
                            "Bahadurpur",
                            "Hudhudwa",
                            "Janpur",
                            "Jorandwa",
                            "Kalidih",
                            "Lemboia",
                            "Sarheta",
                            "Darai",
                            "Karno",
                            "Kharkhar",
                            "Lahariatand",
                            "Nawalshahi",
                            "Paharpur",
                            "Paisra",
                            "Ratanpur",
                            "Suarleta",
                            "Uparbad",
                            "Chondhi",
                            "Ghuthia",
                            "Katahi",
                            "Kundidhanwar",
                            "Nimadih",
                            "Paranwatand.",
                            "Tikopada",
                            "Bhelwatand",
                            "Golgo",
                            "Langraparas",
                            "Madhuban",
                            "Mahkundi",
                            "Naitand",
                            "Simaria",
                            "Durodih",
                            "Mahthadih",
                            "Asnabad",
                            "Dhumadih",
                            "Masmohana",
                            "Ambatari",
                            "Bagrojot",
                            "Baswaria",
                            "Chatro",
                            "Jiyoraidih",
                            "Kanjiardih",
                            "Masnodih",
                            "Panchgawan",
                            "Ramdih",
                            "Jeruadih",
                            "Nawadih…",
                            "Rupandih",
                            "Chilsodih",
                            "Dhubba",
                            "Jamtara",
                            "Jodasimar",
                            "Nawadih..",
                            "Parho",
                            "Puto",
                            "Bigha.",
                            "PHULWARIYA",
                            "Bisodih",
                            "Karmandih",
                            "Khargu",
                            "Nawada.",
                            "Purnadih",
                            "Raidih",
                            "Bangaikalan",
                            "Karakhut",
                            "Nerpur",
                            "TETARIYADIH"
                        ]
                    },
                    {
                        "name": "Jainagar",
                        "villages": [
                            "Alho",
                            "Amjo",
                            "Badki Ledhiya",
                            "Beko",
                            "Birwatand",
                            "Chhotki Ledhiya",
                            "Nawadih",
                            "Pandiyadih",
                            "Tudmi",
                            "Biharo",
                            "Chandarpur",
                            "Chehal",
                            "Dhusai",
                            "Dumri",
                            "Papramo",
                            "Udalo",
                            "Baniadih",
                            "Dandadih",
                            "Fakaredih",
                            "Jhalpo",
                            "Kanjhiyadih",
                            "Lohadanda",
                            "Manjhgawan",
                            "Modidih",
                            "Salaiya",
                            "Gadgi",
                            "Parsabad",
                            "Gharaunja",
                            "Ghurmunda",
                            "Mahuagarha",
                            "Musauwa",
                            "Bhuwaldih",
                            "Gohal",
                            "Makatpur",
                            "Nandodih",
                            "Gangamo",
                            "Hirodih",
                            "Koshmadih",
                            "Maheshmarai",
                            "Rebhanadih",
                            "Simratand",
                            "Tetariyadih",
                            "Belkatri",
                            "Jainagar",
                            "Bhagandih",
                            "Gopaldih",
                            "Irgobad",
                            "Jainagar",
                            "Pahridih",
                            "Santh",
                            "Bhinkudih",
                            "Gamharbad",
                            "Godakhar",
                            "Kakarcholi",
                            "Mahuatand",
                            "Paharpur",
                            "Tarwan",
                            "Banjhedih",
                            "Dumardiha",
                            "Kandrapdih",
                            "Khedobar",
                            "Koshmadih.",
                            "Rajaidih",
                            "Singardih",
                            "Sonudih",
                            "Baradih",
                            "Dahuatola",
                            "Ghanghari",
                            "Kariyawan",
                            "Kokahradhab",
                            "Kushahan",
                            "Sugasankh",
                            "Katahadih",
                            "Kheskari",
                            "Sahebadih",
                            "Jhalakdih",
                            "Katia",
                            "Alagdiha",
                            "Berogain",
                            "Gariai",
                            "Khariyodih",
                            "Kharpoka",
                            "Kurumdiha",
                            "Pispiro",
                            "Yadudih",
                            "Devitand",
                            "Khuha",
                            "Mesaundha",
                            "Naitand",
                            "Pathalkudwa",
                            "Raghuniadih",
                            "Daldalia",
                            "Ghaghdih",
                            "Khagradih",
                            "Pipcho",
                            "Titahia",
                            "Arwatand",
                            "Baghmara",
                            "Chadra Pipradih",
                            "Gudguddi",
                            "Madhwatand",
                            "Patishale",
                            "Rupaidih",
                            "Baddiha",
                            "Jariai",
                            "Kachaknal",
                            "Karnosaran",
                            "Katharatand",
                            "Kuskur",
                            "Latbedhwa",
                            "Nawada",
                            "Sarmatand",
                            "Satdiha",
                            "Bigha",
                            "Bisodih",
                            "Chak",
                            "Chutiaro",
                            "Dharaidih",
                            "Manjhgawan.",
                            "Sonpura",
                            "Tamai",
                            "Ambadih",
                            "Badulia",
                            "Kenduatand",
                            "Matauni",
                            "Nawadih",
                            "Pandu",
                            "Tetroun",
                            "Behradih",
                            "Tilokri",
                            "Bagodih",
                            "Bhinkodih",
                            "Garchanch",
                            "Mandaria",
                            "Pratappur",
                            "Yogiyatilha"
                        ]
                    },
                    {
                        "name": "Koderma",
                        "villages": [
                            "Bekobar (CT)",
                            "Bhandarwa",
                            "Chandedih",
                            "Pipradih",
                            "Sangramdih",
                            "Bekobar (CT)",
                            "Charadih",
                            "Chutiyaro",
                            "Gadedih",
                            "Kariyabar",
                            "Puto",
                            "Sujanpur",
                            "Chechai",
                            "Chhatarbar",
                            "Chilhitand",
                            "Dobrajpur",
                            "Jungle Sarkar",
                            "Mahuatand",
                            "Renganiatand",
                            "Simratari",
                            "Belgarha",
                            "Dumardiha",
                            "Kharkharo",
                            "Sondedih",
                            "Chitarpur",
                            "Gendwadih Bisunpure",
                            "Inderwa",
                            "Jharitand",
                            "Karharia",
                            "Malkoko",
                            "Nawadih",
                            "Salaidih",
                            "Barhoria",
                            "Belatand",
                            "Bishunpur",
                            "Dhodharpania",
                            "Hathuwadharan",
                            "Jarga",
                            "Jharki Alias Tatgain",
                            "Karmatari",
                            "Pichhli",
                            "Sapha",
                            "Doiadih",
                            "Jhumri",
                            "Kanungobigha",
                            "Karma (CT)",
                            "Lalmandigthu",
                            "Karma (CT)",
                            "Ambakola",
                            "Chanako",
                            "Goriato",
                            "Kauawar Gajhandi",
                            "Meghatari",
                            "Dhebuadih",
                            "Golwadhab",
                            "Jhagrahi",
                            "Karipahri",
                            "Kharkotta",
                            "Bajladih",
                            "Birjamu",
                            "Buchitand(Raghwadih)",
                            "Kolgarma",
                            "Phulwariya",
                            "Anantdih",
                            "Birinda",
                            "Chaturdih",
                            "Dewanidhab",
                            "Garaidih",
                            "Garhai",
                            "Lariyadih",
                            "Naitand",
                            "Baddiha",
                            "Bansdharwa",
                            "Barlotand",
                            "Kundai",
                            "Lokai",
                            "Maliyai",
                            "Tintara",
                            "Bishunitikar",
                            "Karharia",
                            "Meghatari",
                            "Kakuriathamai",
                            "Khairidih",
                            "Pandedih",
                            "Ratithmai",
                            "Singhpur",
                            "Baheradih",
                            "Kamaidih",
                            "Pathaldiha",
                            "Salaia",
                            "Chandrodih",
                            "Lochanpur",
                            "Mahthadih",
                            "Nauadih",
                            "Purnanagar",
                            "Shahpur",
                            "Sijua",
                            "Sitwa Junrormin"
                        ]
                    },
                    {
                        "name": "Markacho",
                        "villages": [
                            "Babhandih",
                            "Bansdih",
                            "Beladih",
                            "Birajpur",
                            "Chopnadih",
                            "Dahuai",
                            "Jagdispur",
                            "Jhalakdih",
                            "Kondradih",
                            "Nagirto",
                            "Araiya",
                            "Asnatari",
                            "Bandarchaukwa",
                            "Banumurha",
                            "Beko",
                            "Dagarnawa",
                            "Daldal",
                            "Jhawatari",
                            "Katio",
                            "Kumbh",
                            "lohabar",
                            "Naudiha",
                            "Parsabad",
                            "Patruniya",
                            "Pichhri",
                            "Simarkundih",
                            "Tepra",
                            "Udalo",
                            "Chilhotand",
                            "Devipur",
                            "Dongodih",
                            "Gurha",
                            "Karmagarha",
                            "Kumardih",
                            "Laludih",
                            "Musobad",
                            "Dasaro Khurd",
                            "Jalaihiya",
                            "Kheraun",
                            "Kushahana",
                            "Harladih",
                            "Jamu",
                            "Kosdihra",
                            "Nadkari",
                            "Bigha",
                            "Denibad",
                            "Gadi",
                            "Gagresinga",
                            "Kadodih",
                            "Ketrusinga",
                            "Manjhladih",
                            "Panduwai",
                            "Raja Raidih",
                            "yogidih",
                            "Barwadih",
                            "debwa",
                            "Geragi",
                            "Lalgarh",
                            "Mahugai",
                            "Sonedih",
                            "Markacho",
                            "Dhubadih",
                            "Markacho",
                            "Papahara",
                            "Bhojpur",
                            "Markacho",
                            "Taradih",
                            "Bariyardih",
                            "Labania Alias Bela",
                            "Murukmanai",
                            "Bahadurpur",
                            "Bakaspura",
                            "Dardahi",
                            "Garagdiha",
                            "Lohandiyo",
                            "Nawadih",
                            "Pandna",
                            "Pipradih",
                            "Ambadih",
                            "Bindhania",
                            "Khandaradih",
                            "Lalkapani Alias Gondardih",
                            "Mahuatand.",
                            "Manik Munda",
                            "Nawadih",
                            "Paplo",
                            "Bhagtiadih",
                            "Karikhokho",
                            "Khesmi Alias Purnanagar",
                            "Pasiadih",
                            "Tolkhar",
                            "Vishunpur Alias Ranginiatand",
                            "Baradih",
                            "Barotand",
                            "Chak",
                            "Dasaro Kala",
                            "Dumardiha",
                            "Mahuatand",
                            "Nariahi",
                            "Simaria",
                            "Arkosa",
                            "Baijladhab",
                            "Bichariya",
                            "Khargu",
                            "Medwapahari",
                            "Naitand",
                            "Nawada",
                            "Pandaria",
                            "Telodih",
                            "Tilaiya"
                        ]
                    },
                    {
                        "name": "Satgawan",
                        "villages": [
                            "Ambabad",
                            "Angar",
                            "Bhuladih",
                            "Karchaita",
                            "Khawasdih",
                            "Khirikala",
                            "Khirikhurd",
                            "Mahthadih",
                            "Mohanria",
                            "Samaidih",
                            "Anandibad",
                            "Bariyardih",
                            "Basodih",
                            "Dedhkurwa",
                            "Dhanhara",
                            "Dumri",
                            "Modidih",
                            "Rajghati",
                            "Rautdih",
                            "Belatand",
                            "Bishnidih",
                            "Butbaria",
                            "Dhuwadih",
                            "Itai",
                            "Jageshwar Kanwarwa",
                            "Jogidih",
                            "Lohar",
                            "Madkupi",
                            "Mohanpur",
                            "Rasaila",
                            "Asnakoni",
                            "Bhakhra",
                            "Deoghar",
                            "Dhab",
                            "Dumduma",
                            "Ghodsimar",
                            "Kataiya",
                            "Khairakala",
                            "Madwa",
                            "Pokhardiha",
                            "Shivrampur",
                            "Bariarpur",
                            "Bhagadih",
                            "Gajedih",
                            "Ghurmudiya",
                            "Jhanjhidih",
                            "Jhinguia",
                            "Jogidih.",
                            "Khuta",
                            "Manorathdih",
                            "Nagri",
                            "Udhokoni",
                            "Anantpur",
                            "Bhartuki",
                            "dharkula",
                            "Donaia",
                            "Ghurshahi",
                            "Hadhadwa",
                            "Jamtoto",
                            "Kanikendra",
                            "Karmo",
                            "Kirtania",
                            "Kothiyar",
                            "Kunda",
                            "Pachane",
                            "Petro",
                            "Ratanpur",
                            "Sethwa",
                            "Simratari",
                            "Bajnia",
                            "Chunadih",
                            "Dhanuki",
                            "Dharampur",
                            "Lembo",
                            "Madhopur",
                            "Newti",
                            "Sarbahna",
                            "Selari",
                            "Baghmara",
                            "Bijhwaria",
                            "Galwati",
                            "Katahara",
                            "Khairakhurd",
                            "Marchoi",
                            "Reserve Forest",
                            "Bhadali",
                            "Danti",
                            "Ghoddaud",
                            "Jhargaon",
                            "Kanikend",
                            "Khairakala",
                            "Maheshdih",
                            "Mananpur",
                            "Mirganj",
                            "Misrichak",
                            "Nawadpur",
                            "Pachoudi",
                            "Pahadpur",
                            "Rajour",
                            "Bad",
                            "Hardia",
                            "Jharahi",
                            "Kairi",
                            "Nawadih",
                            "Tamoria",
                            "Baigna",
                            "Chhapri",
                            "Debodih",
                            "Dedho",
                            "Hardi",
                            "Harilawa",
                            "Jogodih",
                            "Lakrahi",
                            "Mochramo",
                            "Phulwaria",
                            "Rajabar",
                            "Chanddih",
                            "Gangdih",
                            "Lakshmandih",
                            "Naraidih",
                            "Nauachak",
                            "Ramdih",
                            "Samaldih",
                            "Sarveydih",
                            "Tulachak",
                            "Baiddih",
                            "Mahthakhaira",
                            "Nasarganj",
                            "Pahar Singh Khaira",
                            "Shivpur",
                            "Sihas",
                            "Gargohia",
                            "Halkusa",
                            "Jagnidih",
                            "Kalidih",
                            "Khab",
                            "Koslo",
                            "Masania",
                            "Masania",
                            "Mathuradih",
                            "Matukdih",
                            "Nandudih",
                            "Panchmoh",
                            "Sahbagi",
                            "Sirmatdih",
                            "Tehro"
                        ]
                    }
                ]
            }
        ]
    }
]



export const seedVillages = async () => {
    try {
        console.log("🌱 Starting village seed...");

        let insertedCount = 0;
        let skippedCount = 0;

        for (const stateData of villageData) {
            // ================================
            // STATE
            // ================================
            const state = await State.findOneAndUpdate(
                {
                    name: stateData.state,
                },
                {
                    $setOnInsert: {
                        name: stateData.state,
                        status: 1,
                    },
                },
                {
                    new: true,
                    upsert: true,
                }
            );

            // ================================
            // DISTRICTS
            // ================================
            for (const districtData of stateData.districts) {
                const district = await District.findOneAndUpdate(
                    {
                        name: districtData.name,
                        stateId: state._id,
                    },
                    {
                        $setOnInsert: {
                            name: districtData.name,
                            stateId: state._id,
                            status: 1,
                        },
                    },
                    {
                        new: true,
                        upsert: true,
                    }
                );

                // ================================
                // BLOCKS
                // ================================
                for (const blockData of districtData.blocks) {
                    const block = await Block.findOneAndUpdate(
                        {
                            name: blockData.name,
                            districtId: district._id,
                        },
                        {
                            $setOnInsert: {
                                name: blockData.name,
                                districtId: district._id,
                                status: 1,
                            },
                        },
                        {
                            new: true,
                            upsert: true,
                        }
                    );

                    // ================================
                    // VILLAGES
                    // ================================
                    if (!Array.isArray(blockData.villages)) {
                        console.log(
                            `⚠️ Villages missing: ${stateData.state} → ${districtData.name} → ${blockData.name}`
                        );

                        continue;
                    }

                    const villages = blockData.villages
                        .filter(
                            (villageName) =>
                                typeof villageName === "string" &&
                                villageName.trim().length > 0
                        )
                        .map((villageName) => ({
                            name: villageName.trim(),
                            stateId: state._id,
                            districtId: district._id,
                            blockId: block._id,
                            status: 1,
                        }));

                    if (villages.length === 0) {
                        continue;
                    }

                    try {
                        const result = await Village.insertMany(villages, {
                            ordered: false,
                        });

                        insertedCount += result.length;

                        console.log(
                            `✅ ${stateData.state} → ` +
                            `${districtData.name} → ` +
                            `${blockData.name}: ` +
                            `${result.length} villages inserted`
                        );
                    } catch (error) {
                        if (error.writeErrors) {
                            const skipped = error.writeErrors.length;

                            const inserted =
                                villages.length - skipped;

                            insertedCount += inserted;
                            skippedCount += skipped;

                            console.log(
                                `⚠️ ${stateData.state} → ` +
                                `${districtData.name} → ` +
                                `${blockData.name}: ` +
                                `${inserted} inserted, ` +
                                `${skipped} skipped`
                            );
                        } else {
                            throw error;
                        }
                    }
                }
            }
        }

        console.log("\n========================================");
        console.log("✅ Village seed completed");
        console.log("========================================");
        console.log(`Inserted : ${insertedCount}`);
        console.log(`Skipped  : ${skippedCount}`);
        console.log("========================================");

    } catch (error) {
        console.error("❌ Village seed failed:", error);
        throw error;
    }
};
